name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Run unit testing
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          cd taxonomy-builder-app/production-app/backend
          pip install -r requirements.txt
      - name: Run unit tests
        run: |
          cd taxonomy-builder-app/production-app/backend


      # Run React tests
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Run npm tests
        run: |
          cd taxonomy-builder-app/production-app/frontend
          npm install
        #npm test

      # Run API tests
      - name: Run API tests
        run : |
          cd taxonomy-builder-app/production-app/backend
        #python -m unittest test_api.py
